// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe_5L6eZqf2xr6gIMAlQxcRfcIR5DFtb0',
    appId: '1:167879086192:web:a8b5c2892048913f30a4b5',
    messagingSenderId: '167879086192',
    projectId: 'aide-1435a',
    authDomain: 'aide-1435a.firebaseapp.com',
    storageBucket: 'aide-1435a.firebasestorage.app',
    measurementId: 'G-MVGE6HG55C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmTpNMu-LvYpQJootpBMu1b1mHLh6fFQg',
    appId: '1:167879086192:android:571fd46e3f82f7ac30a4b5',
    messagingSenderId: '167879086192',
    projectId: 'aide-1435a',
    storageBucket: 'aide-1435a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLB7qmhfVux5xhJeNunjBowPY5e1o3IaI',
    appId: '1:167879086192:ios:2fd99b29bd16638630a4b5',
    messagingSenderId: '167879086192',
    projectId: 'aide-1435a',
    storageBucket: 'aide-1435a.firebasestorage.app',
    iosBundleId: 'com.example.aide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLB7qmhfVux5xhJeNunjBowPY5e1o3IaI',
    appId: '1:167879086192:ios:2fd99b29bd16638630a4b5',
    messagingSenderId: '167879086192',
    projectId: 'aide-1435a',
    storageBucket: 'aide-1435a.firebasestorage.app',
    iosBundleId: 'com.example.aide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe_5L6eZqf2xr6gIMAlQxcRfcIR5DFtb0',
    appId: '1:167879086192:web:44c021c60c69b03d30a4b5',
    messagingSenderId: '167879086192',
    projectId: 'aide-1435a',
    authDomain: 'aide-1435a.firebaseapp.com',
    storageBucket: 'aide-1435a.firebasestorage.app',
    measurementId: 'G-TSC9BW36KK',
  );
}
